language: python

python:
  - '3.6'

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - black --check
  - flake8
  - coverage run --source='.' manage.py test mysite
  - coveralls